name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.11.0
    - name: Setup Redis
      uses: zhulik/redis-action@1.1.0
    - run: npm install
    - run: npm run lint
    - run: npm run build --if-present
    - run: npm run test-all
      env:
        CI: true
